language: c
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

env: FC=gfortran

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: gfortran-8

matrix:
  include:
  - os: linux
    env: FC=gfortran-8

install:
- mkdir build
- cd build
- cmake .. -DSERIAL=1 
- make
    
script: ctest --output-on-failure
