name = "neural-fortran"
version = "0.5.0"
license = "MIT"
author = "Milan Curcic"
maintainer = "milancurcic@hey.com"
copyright = "Copyright 2018-2022, neural-fortran contributors"

[build]
external-modules = "hdf5"
link = ["hdf5", "hdf5_fortran"]

[dependencies]
h5fortran = { git = "https://github.com/geospace-code/h5fortran" }
json-fortran = { git = "https://github.com/jacobwilliams/json-fortran" }
