name = "neural-fortran"
version = "0.5.0"
license = "MIT"
author = "Milan Curcic"
maintainer = "milancurcic@hey.com"
copyright = "Copyright 2018-2022, neural-fortran contributors"

// The following HDF5 stuff could move to h5fortran's fpm.toml
[build]
external-modules = ["hdf5", "h5lt"]
link = ["hdf5", "hdf5_hl", "hdf5_fortran", "hdf5hl_fortran"]

[dependencies]
h5fortran = { git="https://github.com/geospace-code/h5fortran" }
